version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor:
      name: win/default
      shell: bash.exe
    steps:
      - run:
        name: Installing Cmake
        command: 'choco install cmake.install --installargs "ADD_CMAKE_TO_PATH=System"'
      - checkout
      - run:
          name: Compiling Code
          command: 'mkdir build && cd build && cmake .. && make'